### PR TITLE
gui: show node number above node type in editor

### PR DESCRIPTION
**Pull request by ynedelec3**
gui: show node number above node type in editor

Related to issue "show node number in node editor #22"

### CODE REVIEW

**Comment by quesnel** [comment]
Last change. Can you change the commit message?
gui: show node...

**Comment by ynedelec3** [comment]
I changed the title, was that the point ?

**Comment by ynedelec3** [comment]
I cannot change the header of commit name itself ("Update node-editor.cpp") -(

**Comment by quesnel** [comment]
Thank you. I merged the code.
I updated the commit message. Github does not permit to change it. I use the git command line interface.
````
git checkout -b ynedelec3-master master
git pull https://github.com/ynedelec3/irritator.git master
git commit --amend # here I change the commit message
git push origin  ynedelec3-master:master
````

**Pull request closed without merging**
