### PR TITLE
Pull request for model:filter on Examplesbranch

### PR DESCRIPTION
**Pull request by ovese**
New Pull request for model filter on examplebranch

### CODE REVIEW

**Review by quesnel — COMMENTED** [review]
Please, can you rebase your branch `ovese:examplesbranch` with `vle-forge:master` [1] to clean up the pull request?

[1] Use these commands (update with correct branch/repo names):
````
git fetch vle-forge
git checkout examplesbranch
git rebase vle-forge/master
````

**Comment by ovese** [comment]
Hello Gauthier,

I am still working with the old fork I created previously. Could this be the problem? Should I create a new repository( new fork) to work on this new task.

Please is this what you want me to do?

**Comment by quesnel** [comment]
Hello,

On mar. 22 juin 21, Ese Ovie wrote:
> I am still working with the old fork I created previously. Could this
> be the problem? Should I create a new repository( new fork) to work on
> this new task.

The best is to only use one fork. But you must maintain your fork with
the central repository (vle-forge/irritator) using git fetch, git
rebase, git merge etc.

For the pull requests, use a new branch and this branch must be with the
same history than vle-forge/master.

**Comment by ovese** [comment]
Using 
git fetch
git rebase
git merge
 Tells me all my files are up to date. I dont know why the conflict remains

**Comment by quesnel** [comment]
On mar. 22 juin 21, Ese Ovie wrote:
> Using 
> git fetch
> git rebase
> git merge
>  Tells me all my files are up to date. I dont know why the conflict remains

The correct functions are:

First, create the remote repository in your fork:

````
git remote add vle-forge https://github.com/vle-forge/irritator.git
````

Second, update and rebase your branch:

````
git fetch vle-forge
git checkout examplesbranch
git rebase vle-forge/master
````

**Comment by ovese** [comment]
Hello Gauthier,
can you check the pull request history and let me know if everything is ok. I see some items are failing while some are ok.

Do you think I should just redo the pull request and discard this one.

**Comment by quesnel** [comment]
I think you can create a new pull request from a clean branch. This pull request comes with too many merge errors.

**Pull request closed without merging**
