### PR TITLE
seir on new featurebranch

### PR DESCRIPTION
**Pull request by ovese**
Added the requested patch t SEIR model. deleted linear model, renamed to all English format and updated the nonlinear SEIR

### CODE REVIEW

**Review by quesnel — CHANGES_REQUESTED** [review]
It seems ok. But can you rename the commit message? I prefer a message like:
````
model: replacing QSS1 linear with QSS2 non linear seir'
````

**Comment by ovese** [comment]
I have modified the commit message as requested
git commit --amend -m "new mesage"
git push --force RN BN
or
git push --force-with-lease RN BN

**Comment by ovese** [comment]
Should i also add a qss1 and qss3 model for the seir_nonlinear model?

**Comment by quesnel** [comment]
> Should i also add a qss1 and qss3 model for the seir_nonlinear model?

Yes. Please. After these two commits (one for QSS1 one for QSS3) I merge your PR.

**Review by quesnel — COMMENTED** [review]
Can you add two commits (one for QSS1 one for QSS3)?
I will merge your PR after.

**Comment by ovese** [comment]
Now after editing the files for model: filter , when I checkout to the featureSeir branch, it asks me the following question:

$ git checkout featureSeir
Unlink of file 'app/gui/node-editor.cpp' failed. Should I try again? (y/n) y
Unlink of file 'app/gui/node-editor.cpp' failed. Should I try again? (y/n) n
error: unable to unlink old 'app/gui/node-editor.cpp': Invalid argument
Updating files: 100% (4/4), done.
Switched to branch 'featureSeir'
M       app/gui/node-editor.cpp
Your branch is ahead of 'vle-forge/master' by 1 commit.
  (use "git push" to publish your local commits)

**Comment by ovese** [comment]
when my response is yes , it does not checkout successfully but if my response is no, it checksout to the featureSeir branch.
 
but now when i go back to my files, i can see the repo the same way it was when I just cloned my repo. I don't understand it

**Comment by quesnel** [comment]
On Fri, Jul 16, 2021 at 05:10:31AM -0700, Ese Ovie wrote:
> when my response is yes , it does not checkout successfully but if my
> response is no, it checksout to the featureSeir branch.
>  
> but now when i go back to my files, i can see the repo the same way it
> was when I just cloned my repo. I don't understand it

Is the file node-editor.cpp open in Visual Studio or another editor?

**Comment by quesnel** [comment]
While compiling the project, I get a lot of warnings. Can you fix it and merge with one of your patchs?

`
../lib/include/irritator/core.hpp:6344:9: warning: enumeration value ‘filter’ not handled in switch [-Wswitch]
 6344 |         switch (mdl.type) {
      |  

../lib/include/irritator/core.hpp:6822:16: warning: enumeration value ‘filter’ not handled in switch [-Wswitch]
 6822 |         switch (mdl_src.type) {
      |                ^

../lib/include/irritator/core.hpp:6463:9: warning: enumeration value ‘filter’ not handled in switch [-Wswitch]
 6463 |         switch (mdl.type) {
      |         ^~~~~~
`

**Comment by ovese** [comment]
Unfortunately, I dont find this error when I compile the project. I dont know why it is this way. but I am still checking the core.hpp to see what the problem might be.

**Comment by ovese** [comment]
Not error...warning. I dont find that warning

**Comment by ovese** [comment]
> While compiling the project, I get a lot of warnings. Can you fix it and merge with one of your patchs?
> 
> `
> ../lib/include/irritator/core.hpp:6344:9: warning: enumeration value ‘filter’ not handled in switch [-Wswitch]
> 6344 | switch (mdl.type) {
> |
> 
> ../lib/include/irritator/core.hpp:6822:16: warning: enumeration value ‘filter’ not handled in switch [-Wswitch]
> 6822 | switch (mdl_src.type) {
> | ^
> 
> ../lib/include/irritator/core.hpp:6463:9: warning: enumeration value ‘filter’ not handled in switch [-Wswitch]
> 6463 | switch (mdl.type) {
> | ^~~~~~
> `

I think this is fixed now. I dont have any warnings from my end when I run the test and also the omissions in the core.hpp file have been handled

**Comment by quesnel** [comment]
Everything is good. I merge, thank you.

**Pull request merged**
