### PR TITLE
model:SEIR qss2power to QssLevel in example

### PR DESCRIPTION
**Pull request by ovese**
Made correction to fix crash report on example.hpp.
Changed the following lines:
 //auto& pow_n = sim.alloc<qss2_power>();
to this
    auto& pow_n = sim.alloc<QssLevel>();

That was the source of the error

### CODE REVIEW

**Comment by ovese** [comment]
Correction made:   
    auto& pow_n = sim.alloc<qss2_power>();
to
    auto& pow_n = sim.alloc<abstract_power<QssLevel>>();

**Comment by ovese** [comment]
//auto& pow_n = sim.alloc<qss2_power>();
    auto& pow_n = sim.alloc<abstract_power<QssLevel>>();

**Comment by quesnel** [comment]
I think you can merge all commits into a single commit:
`model:SEIR updated abstract sum coefficients`: introduces an error on an error
`model: SEIR power variable edited in example`: fix the previous error
`model:SEIR updated abstract sum coefficients`: bad commit message, update the number of input port (not the abstract sum coefficients)
`model:SEIR qss2power to QssLevel in example`: bad commit message, fix a bad input port

**Comment by ovese** [comment]
> I think you can merge all commits into a single commit:
> `model:SEIR updated abstract sum coefficients`: introduces an error on an error
> `model: SEIR power variable edited in example`: fix the previous error
> `model:SEIR updated abstract sum coefficients`: bad commit message, update the number of input port (not the abstract sum coefficients)
> `model:SEIR qss2power to QssLevel in example`: bad commit message, fix a bad input port

oK. will rebase and merge commits

**Comment by ovese** [comment]
merged commits on branch featureSeir

**Review by quesnel — CHANGES_REQUESTED** [review]
Can you rename your commit message? I suggest:
`model: fixing SEIR model crash`

**Comment by ovese** [comment]
> Can you rename your commit message? I suggest:
> `model: fixing SEIR model crash`

I have made all corrrections and I am coming up with linux based errors when pushing to my remote master
Same thing happens in Seir and filter branch

**Comment by ovese** [comment]
I am reading the error report actions section and I dont se anything regarding my edited files or the code but the report has to do with Linux

Err:5 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libegl-mesa0 amd64 21.0.3-0ubuntu0.2~20.04.1
  404  Not Found [IP: 52.154.174.208 80]
Err:17 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libgl1-mesa-dev amd64 21.0.3-0ubuntu0.2~20.04.1
  404  Not Found [IP: 52.154.174.208 80]

**Comment by ovese** [comment]
Al checks are passed here too

**Comment by quesnel** [comment]
All is good. Just add a single space after `:` in the commit message and change the message:
From `model:SEIR qss2power to QssLevel` to `model: fix SEIR models`

**Comment by ovese** [comment]
Modified the commit message as requested

**Comment by quesnel** [comment]
Good!
Merged, Thx.

**Pull request merged**
