### PR TITLE
qss1 seir exampleshpp patch

### PR DESCRIPTION
**Pull request by ovese**
Bonjour Gauthier, Je ne c'est pas qu'est-ce que j'avait fait. Parceque je ne trouve pas mon repo avec seirdeux. Peut-etre je supprimee par erreur

### CODE REVIEW

**Comment by ovese** [comment]
Hello Gauthier,
I have created a new pull request. I have commited the two files examples.hpp and node-editor.cpp separately and the oush has been done

**Review by quesnel — CHANGES_REQUESTED** [review]
The code is good!

Could you just rename your commit messages? We use classical rules (search "git commit message" on google).

````
xxxx: yyyyyyyyyyyyyyyyy

zzzzzzzz
zzzzzzzz
zzzzzzzz
````

`xxxx` is the part of the code you modify (examples, gui, main, core etc.).
`yyyyyyy` a short message
`zzzz....` a long explanation message.

So. Instead of `qss1 seir exampleshpp patch`, prefers:
`examples: add qss1 seir model`

And instead of `qss1 seir node-editorcpp patch` prefers:
`gui: add qss1 seir model in node-editor`.

**Comment by quesnel** [comment]
I am sorry but you miss the `xxxx:`  part of the short commit message.
This is an important part when you need to sort patches.

**examples:** add qss1 seir model
**gui:** add qss1 seir model in node-editor

**Comment by ovese** [comment]
I have renamed the files as req1uested. Please pardon my late response

**Review by quesnel — APPROVED** [review]

**Comment by quesnel** [comment]
Perfect. Thx !

**Pull request merged**
